security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    role_hierarchy:
        ROLE_ADMIN: ROLE_CLIENT
    encoders:
        App\Entity\Utilisateur:
            algorithm: bcrypt
            cost: 12
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            logout:
                path: app_logout
                target: index
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/(%app.supported_locales%)/admin, roles: ROLE_ADMIN }
        - { path: ^/(%app.supported_locales%)/usager/accueil, roles: ROLE_CLIENT }
        - { path: ^/(%app.supported_locales%)/usager/commandes, roles: ROLE_CLIENT }
