#index:
#    controller: App\Controller\HomeController::index
home:
  path: /{_locale}/
  controller: App\Controller\DefaultController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

contact:
  path: /{_locale}/contact
  controller: App\Controller\DefaultController::contact
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

boutique:
  path: /{_locale}/boutique
  controller: App\Controller\BoutiqueController::boutique
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

utilisateur_accueil:
  path: /{_locale}/utilisateur_accueil
  controller: App\Controller\UtilisateurController::index
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr

utilisateur_inscription:
  path: /{_locale}/inscription
  controller: App\Controller\UtilisateurController::new
  requirements:
    _locale: '%app.supported_locales%'
  defaults:
    _locale: fr